unit_05/mysite/blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    
    # ex: /blog/
    url(r'^$', views.index, name='index'),
    url(r'^news/$', views.news, name='news'),
    url(r'^2016/$', views.special_case_2016),
    url(r'^latest/$', views.latest),
    
    # ex: /blog/5/
    url(r'^(?P<blog_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /blog/5/results/
    # url(r'^(?P<blog_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /blog/5/vote/
    url(r'^(?P<blog_id>[0-9]+)/vote/$', views.vote, name='vote'),

    
    url(r'^([0-9]{4})/$', views.year_archive),
    url(r'^([0-9]{4})/([0-9]{2})/$', views.month_archive),
    url(r'^([0-9]{4})/([0-9]{2})/([0-9]+)/$', views.article_detail),

    url(r'^(?P<year>[0-9]{4})/$', views.year_archive),
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', views.month_archive),
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/$', views.article_detail),
]

unit_05/mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from home import views as view_home

urlpatterns = [
    url(r'^$', view_home.home, name='home'),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^admin/', admin.site.urls),
]

unit_05/mysite/blog/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible

class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True, verbose_name='slug')
    description = models.TextField(max_length=4096)

    def __str__(self):
        return '%s' % (self.name)

class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True, verbose_name='slug')

    def __str__(self):
        return '%s' % (self.name)

@python_2_unicode_compatible
class Article(models.Model):
    ARTICLE_STATUS = (
        ('D', 'Not Reviewed'),
        ('P', 'Published'),
        ('E', 'Expired'),
    )
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True, verbose_name='slug')
    status = models.IntegerField(default=0)
    content = models.TextField()
    status = models.CharField(max_length=1, choices=ARTICLE_STATUS, default='D')
    category = models.ForeignKey(Category, verbose_name="the related category")
    tags = models.ManyToManyField(Tag, verbose_name="the related tags", blank=True)
        
    publish_date = models.DateTimeField(auto_now=True, editable=False, help_text="Please use the following format: <em>YYYY-MM-DD</em>.")
    created_date = models.DateTimeField(auto_now_add=True, editable=False)

    def was_published_recently(self):
        return self.publish_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'publish_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def __str__(self):
        return '%s' % (self.title)

unit_05/mysite/blog/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from .models import Article, Category
import datetime

def special_case_2016(request):
    items = Article.objects.filter(publish_date__year=2016)  
    return render(request, "blog/special_case_2016.html", {'items':items})

def latest(request):
    items = Article.objects.filter(title__startswith='QuerySet').filter(publish_date__gte=datetime.date(2015, 1, 1))  
    
    return render(request, "blog/special_case_2016.html", {'items':items})

def year_archive(request,yy):
    item = {'title':'Year Archive','content':yy}    
    return render(request, "blog/year_archive.html", {'item':item})

def month_archive(request,yy,mm):
    item = {'title':'Month Archive','content':yy}    
    return render(request, "blog/month_archive.html", {'item':item})

def article_detail(request,yy,mm,id):
    item = {'title':'Article Detail','content':id}    
    return render(request, "blog/article_detail.html", {'item':item})

def index(request):
    blog_list = Article.objects.order_by('-publish_date')
    context = {'blog_list': blog_list}
    return render(request, 'blog/index.html', context)

def news(request):
    blog_list = Article.objects.filter(category__name='news')
    context = {'blog_list': blog_list}
    return render(request, 'blog/index.html', context)

def detail0(request, blog_id):
    return HttpResponse("You're looking at article %s." % blog_id)

def detail1(request, blog_id):
    item = Article.objects.get(pk=blog_id)
    
    return render(request, 'blog/detail.html', {'item': item})

def detail(request, blog_id):
    try:
        item = Article.objects.get(pk=blog_id)
    except Article.DoesNotExist:
        raise Http404("Article does not exist")
    return render(request, 'blog/detail.html', {'item': item})

def detail(request, blog_id):
    item = get_object_or_404(Article, pk=blog_id)
    return render(request, 'blog/detail.html', {'item': item})

def vote(request, blog_id):
    return HttpResponse("You're voting on article %s." % blog_id)    

unit_05/mysite/templates/blog/detail.html
{% extends "base.html" %}
{% block head_title %}My Cool Django Blog{% endblock %}

{% block content %} 
      <!-- row of columns -->
      <div class="row">
        <div class="col-md-8">
          <h2>{{ item.title }}</h2>
          <p> {{ item.content }} </p>
          <p> {{ item.publish_date }} </p>
          <p><a class="btn btn-default" href="{% url 'blog:index' %}" role="button">All publications &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        
      </div>

{% endblock content %}

unit_05/mysite/templates/blog/index.html
{% extends "base.html" %}
{% block head_title %}My Cool Django Blog{% endblock %}

{% block content %} 
      <!-- row of columns -->
      <div class="row">
        <div class="col-md-8">
          <h2>Publications</h2>
              {% if blog_list %}
                {% for item in blog_list %}
                  <h3><a href ="{% url 'blog:detail' item.id %}">{{ item.title }}</a></h3>
                    <p><a class="btn btn-default" href="{% url 'blog:detail' item.id %}" role="button">View details &raquo;</a></p>
                {% endfor %}
              {% else %}
                <li>Sorry, no items in this list.</li>
              {% endif %}
          
        </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        
      </div>

{% endblock content %}