unit_15/mysite/blog/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required as auth

from . import views

urlpatterns = [

    url(r'^$', views.index, name='index'),
    #url(r'^news/$', views.news, name='news'),
    url(r'^news/$', views.HomeView.as_view(), name='news'),

    url(r'^latest/$', views.latest),
    url(r"^archive/(\d+)/(\d+)/$", views.monthly_archive , name='archive'),
    url(r'^category/(?P<categoryslug>.*)/$', views.category, name='category' ),

    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/(?P<pk>\d+)-(?P<slug>[-\w]*)/$', views.ArticleDetail.as_view(), name='entry_detail'),
    
    url(r'^(?P<postslug>.*)/$', views.detail, name='detail' ),

]

unit_15/mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from home import views as view_home

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from django.views.generic.base import RedirectView, TemplateView

urlpatterns = [
    # Root-level redirects for common browser requests
    url(r'^favicon\.ico$', RedirectView.as_view(url=settings.STATIC_URL + 'img/compressed/favicon.ico'), name='favicon.ico'),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain'), name='robots.txt'),
]

urlpatterns += [
    url(r'^$', view_home.home, name='home'),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^users/', include('userprofiles.urls', namespace="users")),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

]

urlpatterns += i18n_patterns(
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^coupons/', include('coupons.urls', namespace='coupons')),

    url(r'^admin/', admin.site.urls),
    )

if settings.DEBUG:
    try:
        from django.conf.urls.static import static
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # Should only occur when debug mode is on for production testing
    except ImportError as e:
        import logging
        l = logging.getLogger(__name__)
        l.warning(e)

unit_15/mysite/userprofiles/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.contrib.auth.decorators import login_required as auth
from . import views

urlpatterns = [

    url(r'^register/$', views.RegistrationView.as_view(), name='userprofiles_registration'),
    url(r'^register/complete/$', views.RegistrationCompleteView.as_view(), name='userprofiles_registration_complete'),

    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name="logout"),

    url(r'^profile/(?P<slug>.*)/$', views.UserProfileDetailView.as_view(), name='profile'),
    url(r'^edit_profile/$', auth(views.UserProfileEditView.as_view()), name='edit_profile'),

   ]

unit_15/mysite/templates/includes/footer.html
{% load staticfiles %}
      <hr>

      <footer>
        <p>&copy; Company 2016</p>
      </footer>
    </div> <!-- /container -->        

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="static/js/vendor/jquery-1.11.0.min.js"><\/script>')</script>

        <script src="{% static 'js/vendor/bootstrap.min.js' %}">
        
        <script src="{% static 'js/plugins.js' %}">
        <script src="{% static 'js/main.js' %}">
        

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X','auto');ga('send','pageview');
        </script>
    </body>
</html>

unit_15/mysite/templates/includes/header.html
{% load staticfiles %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> 
<html class="no-js" lang=""> 
<!--<![endif]-->
    <head>
        <title>{% block head_title %}{% endblock %}</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="apple-touch-icon.png">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        
        <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
        </style>
        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        
        <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>


    </head>
    <body>        

unit_15/mysite/templates/includes/mainmenu.html
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Janus Site</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">

          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Home <span class="sr-only">(current)</span></a></li>
            <li><a href="/blog">Blog</a></li>
            <li><a href="/blog/news">News</a></li>
            <li><a href="/shop">Shop</a></li>
          </ul>

          <ul class="nav  navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li><a href="{% url 'users:logout' %}">Logout</a></li>
            <li><a href="{% url 'users:profile' slug=user.username %}">{{ user.username }}</a></li>
            {% else %}
            <li><a href="{% url 'users:userprofiles_registration' %}">Register</a></li>
            <li><a href="{% url 'users:login' %}">Login</a></li>
          {% endif %}
         </ul>

        </div><!--/.navbar-collapse -->
      </div>
    </nav>